"""World: the simulation container, its deterministic setup, and its snapshot.

Design decisions (see PLAN.md, Milestone 1):
- **Toroidal, agents-only (v1).** Space wraps on every axis (no walls, no edge
  effects); plants and other entities come in later milestones. The world is
  dimension-agnostic: `size` is a `Vector` of per-axis extents, so the same code
  runs a 2D plane or a 3D box.
- **Deterministic setup (iron laws 7, 8).** Everything random flows from one
  injected `Rng`. Initialization derives *named* sub-streams (`worldgen`, then
  `genome/i` / `pos/i` per agent) so the same seed reproduces the same starting
  world, and adding draws in one place can't shift another (see `rng.py`).
- **The World owns the id counter (iron law 7).** Ids are handed out by a single
  monotonic counter here, never generated by the Agent.
- **Brains stay swappable (iron law 5).** The World does NOT import a concrete
  brain. It receives a `brain_factory: (Genome) -> DecisionMaker` and calls it at
  birth, so swapping the rule-based brain for a neural net later touches only the
  factory the caller passes in -- not this module.
- **Params are injected (iron law 10).** `PhenotypeParams` and the genome schema
  come from `config` via the caller; the World hardcodes none of them.
- **Snapshots are pure data (iron laws 1, 2).** `snapshot()` returns an immutable
  `WorldSnapshot` of plain values. The rendering layer consumes only that and
  never reaches into live `Agent` objects.

This sub-step builds the container, deterministic population, and the snapshot.
The two-phase tick (decide -> resolve) and the data-recording hook land next.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from core.agent import Agent
from core.decision.base import DecisionMaker
from core.genome import ChromosomeSpec, Genome
from core.phenotype import PhenotypeParams, express
from core.rng import Rng
from core.vector import Vector

BrainFactory = Callable[[Genome], DecisionMaker]


# --- pure-data snapshots (rendering layer consumes only these) ----------------

@dataclass(frozen=True, slots=True)
class AgentSnapshot:
    """An immutable readout of one agent at a moment in time.

    Carries what a renderer or recorder needs without exposing the live Agent:
    pose (`position`, `heading`, `body_radius`) for drawing, `size`/`diet` for
    colour, `energy` for debug overlays, `alive` for filtering.
    """

    id: int
    position: Vector
    heading: Vector
    body_radius: float
    energy: float
    size: float
    diet: float
    alive: bool


@dataclass(frozen=True, slots=True)
class WorldSnapshot:
    """An immutable readout of the whole world at one tick."""

    tick: int
    size: Vector
    agents: tuple[AgentSnapshot, ...]


# --- the world ----------------------------------------------------------------

class World:
    """Container for the live simulation state plus deterministic setup."""

    __slots__ = (
        "size",
        "agents",
        "tick_count",
        "_rng",
        "_schema",
        "_phenotype_params",
        "_brain_factory",
        "_next_id",
    )

    def __init__(
        self,
        size: Vector,
        rng: Rng,
        *,
        schema: tuple[ChromosomeSpec, ...],
        phenotype_params: PhenotypeParams,
        brain_factory: BrainFactory,
    ) -> None:
        if any(extent <= 0 for extent in size):
            raise ValueError("every world extent must be positive")
        self.size = size
        # Keyed by id: O(1) target lookup for EatAction in the resolve phase, and
        # dict preserves insertion (== id) order, keeping iteration deterministic.
        self.agents: dict[int, Agent] = {}
        self.tick_count = 0
        self._rng = rng
        self._schema = schema
        self._phenotype_params = phenotype_params
        self._brain_factory = brain_factory
        self._next_id = 0

    # --- id allocation (World owns the counter, iron law 7) -------------------

    def _allocate_id(self) -> int:
        new_id = self._next_id
        self._next_id += 1
        return new_id

    # --- geometry -------------------------------------------------------------

    def wrap(self, position: Vector) -> Vector:
        """Wrap a position into the toroidal world (modulo each axis extent)."""
        if position.dim != self.size.dim:
            raise ValueError("position dimension does not match world dimension")
        return Vector.from_iterable(
            comp % extent for comp, extent in zip(position, self.size)
        )

    # --- birth ----------------------------------------------------------------

    def spawn_agent(
        self,
        genome: Genome,
        position: Vector,
        *,
        energy: float = 0.0,
        generation: int = 0,
    ) -> Agent:
        """Create an agent from a genome: express its phenotype + brain, assign an
        id, wrap it into the torus, and register it. Returns the new Agent."""
        phenotype = express(genome, self._phenotype_params)
        brain = self._brain_factory(genome)
        agent = Agent(
            self._allocate_id(),
            genome,
            phenotype,
            self.wrap(position),
            energy=energy,
            generation=generation,
            decision_maker=brain,
        )
        self.agents[agent.id] = agent
        return agent

    def populate(self, count: int, *, initial_energy: float) -> None:
        """Deterministically fill the world with `count` random agents.

        Same (world seed, count) -> identical starting population. Each agent's
        genome and position draw from their own named sub-streams so the layout is
        stable even if draw counts change elsewhere.
        """
        if count < 0:
            raise ValueError("count cannot be negative")
        gen_rng = self._rng.spawn("worldgen")
        for i in range(count):
            genome = Genome.random(self._schema, gen_rng.spawn(f"genome/{i}"))
            pos_rng = gen_rng.spawn(f"pos/{i}")
            position = Vector.from_iterable(
                pos_rng.uniform(0.0, extent) for extent in self.size
            )
            self.spawn_agent(
                genome, position, energy=initial_energy, generation=0
            )

    # --- inspection -----------------------------------------------------------

    def snapshot(self) -> WorldSnapshot:
        """Take an immutable, pure-data readout of the world for rendering."""
        agents = tuple(
            AgentSnapshot(
                id=a.id,
                position=a.position,
                heading=a.heading,
                body_radius=a.phenotype.body_radius,
                energy=a.energy,
                size=a.genome.get("size"),
                diet=a.genome.get("diet"),
                alive=a.alive,
            )
            for a in self.agents.values()
        )
        return WorldSnapshot(tick=self.tick_count, size=self.size, agents=agents)

    def __repr__(self) -> str:
        return (
            f"World(tick={self.tick_count}, agents={len(self.agents)}, "
            f"size={self.size})"
        )
