"""World: the simulation container, its deterministic setup, and its snapshot.

Design decisions (see PLAN.md, Milestone 1):
- **Toroidal, agents-only (v1).** Space wraps on every axis (no walls, no edge
  effects); plants and other entities come in later milestones. The world is
  dimension-agnostic: `size` is a `Vector` of per-axis extents, so the same code
  runs a 2D plane or a 3D box.
- **Deterministic setup (iron laws 7, 8).** Everything random flows from one
  injected `Rng`. Initialization derives *named* sub-streams (`worldgen`, then
  `genome/i` / `pos/i` per agent) so the same seed reproduces the same starting
  world, and adding draws in one place can't shift another (see `rng.py`).
- **The World owns the id counter (iron law 7).** Ids are handed out by a single
  monotonic counter here, never generated by the Agent.
- **Brains stay swappable (iron law 5).** The World does NOT import a concrete
  brain. It receives a `brain_factory: (Genome) -> DecisionMaker` and calls it at
  birth, so swapping the rule-based brain for a neural net later touches only the
  factory the caller passes in -- not this module.
- **Params are injected (iron law 10).** `PhenotypeParams` and the genome schema
  come from `config` via the caller; the World hardcodes none of them.
- **Snapshots are pure data (iron laws 1, 2).** `snapshot()` returns an immutable
  `WorldSnapshot` of plain values. The rendering layer consumes only that and
  never reaches into live `Agent` objects.

This sub-step builds the container, deterministic population, and the snapshot.
The two-phase tick (decide -> resolve) and the data-recording hook land next.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from core.agent import Agent
from core.decision.base import (
    Action,
    DecisionMaker,
    EatAction,
    MoveAction,
    PerceivedAgent,
    PerceivedPlant,
    Perception,
)
from core.genome import ChromosomeSpec, Genome
from core.phenotype import PhenotypeParams, express
from core.plant import Plant, PlantParams
from core.recording import NullRecorder, Recorder
from core.reproduction.base import Reproducer
from core.rng import Rng
from core.spatial import UniformGrid
from core.vector import Vector

BrainFactory = Callable[[Genome], DecisionMaker]


def random_unit_vector(dim: int, rng: Rng) -> Vector:
    """An isotropic random unit vector (Gaussian per component, then normalize).

    Dimension-agnostic. Public so the seeding harness (main.py) can give created
    agents a random facing too. (Mirrors the helper in `decision.rule_based`, which
    keeps its own copy to avoid depending on this module.)
    """
    v = Vector(*(rng.gauss(0.0, 1.0) for _ in range(dim)))
    if v.length_squared() == 0.0:
        return Vector(*([1.0] + [0.0] * (dim - 1)))  # astronomically unlikely
    return v.normalized()


# --- pure-data snapshots (rendering layer consumes only these) ----------------

@dataclass(frozen=True, slots=True)
class AgentSnapshot:
    """An immutable readout of one agent at a moment in time.

    Carries what a renderer or recorder needs without exposing the live Agent:
    pose (`position`, `heading`, `body_radius`) for drawing, `size`/`diet` for
    colour, `energy` for debug overlays, `alive` for filtering.
    """

    id: int
    position: Vector
    heading: Vector
    body_radius: float
    energy: float
    size: float
    diet: float
    alive: bool


@dataclass(frozen=True, slots=True)
class PlantSnapshot:
    """An immutable readout of one plant for rendering."""

    id: int
    position: Vector
    body_radius: float


@dataclass(frozen=True, slots=True)
class WorldSnapshot:
    """An immutable readout of the whole world at one tick."""

    tick: int
    size: Vector
    agents: tuple[AgentSnapshot, ...]
    plants: tuple[PlantSnapshot, ...]


# --- predation economy (world-authoritative) ----------------------------------

@dataclass(frozen=True, slots=True)
class PredationParams:
    """Tunable, world-side predation coefficients (iron law 10).

    These belong to the World, the authority on what *physically* happens, and are
    deliberately separate from the brain's own copy of `predation_size_ratio` (which
    is only the brain's *belief* about who it can hunt). In v1 both come from the same
    config number, but keeping two sources lets a future brain misjudge a kill while
    the world still adjudicates correctly ("brain proposes, world disposes").

    - `size_ratio`: a predator must exceed `size_ratio` times the prey's `size` gene to
      make the kill.
    - `body_value_coeff`: a slain prey is worth its energy reserves PLUS structural
      biomass `body_value_coeff * body_radius**2` (area ~ mass in 2D), so a large prey
      is a big meal even when starving ("a camel starved to death still outweighs a
      horse"). The whole meal is then scaled by the predator's carnivory efficiency
      `prey_gain` -- which, with carn_max > 1, makes meat energy-dense by design.
    """

    size_ratio: float
    body_value_coeff: float

    def __post_init__(self) -> None:
        if self.size_ratio <= 0:
            raise ValueError("predation size_ratio must be positive")
        if self.body_value_coeff < 0:
            raise ValueError("predation body_value_coeff cannot be negative")


# --- the world ----------------------------------------------------------------

class World:
    """Container for the live simulation state plus deterministic setup."""

    __slots__ = (
        "size",
        "agents",
        "plants",
        "tick_count",
        "_rng",
        "_schema",
        "_phenotype_params",
        "_brain_factory",
        "_next_id",
        "_recorder",
        "_plant_params",
        "_predation_params",
        "_reproducer",
        "_offspring_placement_factor",
        "_spatial_cell_size",
    )

    def __init__(
        self,
        size: Vector,
        rng: Rng,
        *,
        schema: tuple[ChromosomeSpec, ...],
        phenotype_params: PhenotypeParams,
        brain_factory: BrainFactory,
        recorder: Recorder | None = None,
        plant_params: PlantParams | None = None,
        predation_params: PredationParams | None = None,
        reproducer: Reproducer | None = None,
        offspring_placement_factor: float = 2.0,
        spatial_cell_size: float = 100.0,
    ) -> None:
        if any(extent <= 0 for extent in size):
            raise ValueError("every world extent must be positive")
        self.size = size
        # Keyed by id: O(1) target lookup for EatAction in the resolve phase, and
        # dict preserves insertion (== id) order, keeping iteration deterministic.
        # Agents and plants share one id space (the same counter) so an
        # EatAction(target_id) resolves unambiguously to one table or the other.
        self.agents: dict[int, Agent] = {}
        self.plants: dict[int, Plant] = {}
        self.tick_count = 0
        self._rng = rng
        self._schema = schema
        self._phenotype_params = phenotype_params
        self._brain_factory = brain_factory
        self._next_id = 0
        # Data-recording seam (iron law 6): default is a no-op sink.
        self._recorder = recorder if recorder is not None else NullRecorder()
        # Plant economy (optional): when set, tick() regrows plants each step.
        self._plant_params = plant_params
        # Predation economy (optional): when None, prey EatActions are ignored.
        self._predation_params = predation_params
        # Reproduction (optional, iron law 5): when None, agents never reproduce.
        # The genetics live in the injected strategy; the World owns the trigger,
        # the (energy-conserving) energy transfer, and offspring placement. The
        # placement factor's canonical value lives in config (iron law 10).
        self._reproducer = reproducer
        self._offspring_placement_factor = offspring_placement_factor
        # Perception acceleration (iron law 10: a pure performance knob, never a
        # result knob). Cell size only changes how the neighbour search is bucketed;
        # the exact range + field-of-view test still decides what is actually seen.
        self._spatial_cell_size = spatial_cell_size

    # --- id allocation (World owns the counter, iron law 7) -------------------

    def _allocate_id(self) -> int:
        new_id = self._next_id
        self._next_id += 1
        return new_id

    # --- geometry -------------------------------------------------------------

    def wrap(self, position: Vector) -> Vector:
        """Wrap a position into the toroidal world (modulo each axis extent)."""
        if position.dim != self.size.dim:
            raise ValueError("position dimension does not match world dimension")
        return Vector.from_iterable(
            comp % extent for comp, extent in zip(position, self.size)
        )

    def toroidal_delta(self, source: Vector, target: Vector) -> Vector:
        """Shortest displacement from `source` to `target` on the torus.

        Minimum-image convention: on each axis, take whichever of "go forward" or
        "wrap around the back" is shorter. This is what makes neighbours on the
        opposite edge count as close.
        """
        if source.dim != self.size.dim or target.dim != self.size.dim:
            raise ValueError("vector dimension does not match world dimension")
        comps = []
        for s, t, extent in zip(source, target, self.size):
            d = (t - s) % extent          # in [0, extent)
            if d > extent / 2.0:
                d -= extent               # wrapping backwards is shorter
            comps.append(d)
        return Vector.from_iterable(comps)

    # --- perception (sector / cone vision) ------------------------------------

    def _visible_delta(
        self,
        observer: Vector,
        target: Vector,
        heading_unit: Vector,
        range_sq: float,
        cos_half: float,
    ) -> Vector | None:
        """Return the relative position of `target` if the observer can see it, else
        None. Visible = within range AND inside the forward cone.

        The field-of-view test is a dot product between the observer's unit heading
        and the unit direction to the target, so it is dimension-agnostic (a 2D
        sector now, a 3D cone later). An entity in contact (same spot) is always
        visible.
        """
        rel = self.toroidal_delta(observer, target)
        dist_sq = rel.length_squared()
        if dist_sq > range_sq:
            return None
        if dist_sq > 0.0 and heading_unit.dot(rel.normalized()) < cos_half:
            return None
        return rel

    def _build_grids(self) -> tuple[UniformGrid[Agent], UniformGrid[Plant]]:
        """Bucket all current agents and plants into fresh spatial grids (O(N)).

        Built once per tick before the decide phase and shared by every agent's
        perception; positions are stable through phase 1, so one build serves all.
        """
        agent_grid: UniformGrid[Agent] = UniformGrid(self.size, self._spatial_cell_size)
        agent_grid.rebuild((a.position, a) for a in self.agents.values())
        plant_grid: UniformGrid[Plant] = UniformGrid(self.size, self._spatial_cell_size)
        plant_grid.rebuild((p.position, p) for p in self.plants.values())
        return agent_grid, plant_grid

    def perceive(
        self,
        agent: Agent,
        agent_grid: UniformGrid[Agent] | None = None,
        plant_grid: UniformGrid[Plant] | None = None,
    ) -> Perception:
        """Gather what `agent` can see this tick into a Perception value object.

        An entity is perceived when it is within `perception_range` by toroidal
        distance and inside the field of view (see `_visible_delta`). Plants and
        agents are filtered by the same vision; a plant behind the agent is unseen.

        The spatial grids are only an accelerator: they pre-select candidate cells
        so we test a handful of nearby entities instead of every one (O(N) per tick
        instead of O(N^2)). `tick()` builds them once and passes them in; a direct
        call (e.g. a test) omits them and gets a one-off build -- results are
        identical either way, since the exact range/FOV test below is unchanged.
        """
        pheno = agent.phenotype
        perception_range = pheno.perception_range
        range_sq = perception_range * perception_range
        cos_half = pheno.perception_cos_half_angle
        heading_unit = agent.heading.normalized()

        if agent_grid is None or plant_grid is None:
            agent_grid, plant_grid = self._build_grids()

        seen_agents: list[PerceivedAgent] = []
        for other in agent_grid.query(agent.position, perception_range):
            if other.id == agent.id or not other.alive:
                continue
            rel = self._visible_delta(
                agent.position, other.position, heading_unit, range_sq, cos_half
            )
            if rel is None:
                continue
            seen_agents.append(
                PerceivedAgent(
                    id=other.id,
                    relative_position=rel,
                    size=other.genome.get("size"),
                    diet=other.genome.get("diet"),
                    body_radius=other.phenotype.body_radius,
                )
            )

        seen_plants: list[PerceivedPlant] = []
        for plant in plant_grid.query(agent.position, perception_range):
            rel = self._visible_delta(
                agent.position, plant.position, heading_unit, range_sq, cos_half
            )
            if rel is None:
                continue
            seen_plants.append(
                PerceivedPlant(
                    id=plant.id,
                    relative_position=rel,
                    body_radius=plant.body_radius,
                )
            )

        return Perception(
            nearby_agents=tuple(seen_agents),
            nearby_plants=tuple(seen_plants),
            own_energy=agent.energy,
            own_phenotype=pheno,
            own_heading=agent.heading,
        )

    # --- birth ----------------------------------------------------------------

    def spawn_agent(
        self,
        genome: Genome,
        position: Vector,
        *,
        heading: Vector | None = None,
        energy: float = 0.0,
        generation: int = 0,
    ) -> Agent:
        """Create an agent from a genome: express its phenotype + brain, assign an
        id, wrap it into the torus, and register it. Returns the new Agent."""
        phenotype = express(genome, self._phenotype_params)
        brain = self._brain_factory(genome)
        agent = Agent(
            self._allocate_id(),
            genome,
            phenotype,
            self.wrap(position),
            heading=heading,
            energy=energy,
            generation=generation,
            decision_maker=brain,
        )
        self.agents[agent.id] = agent
        return agent

    def re_express_agent(self, agent: Agent) -> None:
        """Rebuild an agent's phenotype AND brain from its current genome.

        The creator-intervention path: after a gene is edited on a live agent
        (demiurge/interventions.py), both the cached phenotype and the brain
        instance are stale -- the brain bakes in the personality genes at
        expression (方案甲). The World re-expresses both because it is the one
        authority that holds the phenotype params and the brain factory; this is
        the same expression `spawn_agent` does at birth, kept in a single place so
        the two cannot drift. Body/metabolism edits change only the phenotype;
        brain-gene edits change only the brain, but rebuilding both is cheap and
        keeps the call correct regardless of which gene moved.
        """
        agent.re_express(self._phenotype_params)
        agent.decision_maker = self._brain_factory(agent.genome)

    def populate(self, count: int, *, initial_energy: float) -> None:
        """Deterministically fill the world with `count` random agents.

        Same (world seed, count) -> identical starting population. Each agent's
        genome and position draw from their own named sub-streams so the layout is
        stable even if draw counts change elsewhere.
        """
        if count < 0:
            raise ValueError("count cannot be negative")
        gen_rng = self._rng.spawn("worldgen")
        for i in range(count):
            genome = Genome.random(self._schema, gen_rng.spawn(f"genome/{i}"))
            pos_rng = gen_rng.spawn(f"pos/{i}")
            position = Vector.from_iterable(
                pos_rng.uniform(0.0, extent) for extent in self.size
            )
            # A random unit facing so directional vision works from birth; its own
            # named sub-stream keeps positions stable regardless of this draw.
            heading = random_unit_vector(self.size.dim, gen_rng.spawn(f"heading/{i}"))
            self.spawn_agent(
                genome, position, heading=heading,
                energy=initial_energy, generation=0,
            )

    # --- plants ---------------------------------------------------------------

    def spawn_plant(self, position: Vector, *, energy: float, body_radius: float) -> Plant:
        """Create a plant at `position` (wrapped into the torus) and register it.
        Shares the agent id counter so EatAction targets stay unambiguous."""
        plant = Plant(self._allocate_id(), self.wrap(position), body_radius, energy)
        self.plants[plant.id] = plant
        return plant

    def scatter_plants(self, count: int, *, energy: float, body_radius: float) -> None:
        """Deterministically scatter `count` plants uniformly at random.

        Uses its own named sub-stream so plant placement is reproducible and
        independent of how many draws the agent population consumed.
        """
        if count < 0:
            raise ValueError("count cannot be negative")
        plant_rng = self._rng.spawn("plantgen")
        for i in range(count):
            pos_rng = plant_rng.spawn(f"pos/{i}")
            position = Vector.from_iterable(
                pos_rng.uniform(0.0, extent) for extent in self.size
            )
            self.spawn_plant(position, energy=energy, body_radius=body_radius)

    def _regrow_plants(self, rng: Rng) -> None:
        """Scatter up to `regen_per_tick` new plants, capped at `max_count`.

        No-op when the world has no plant economy (`plant_params` is None). Because
        this runs every tick, the food supply recovers even after being grazed flat
        -- it can never be permanently eaten to zero.
        """
        pp = self._plant_params
        if pp is None:
            return
        room = pp.max_count - len(self.plants)
        to_add = min(pp.regen_per_tick, room)
        for i in range(to_add):  # to_add <= 0 -> no iterations
            pos_rng = rng.spawn(f"pos/{i}")
            position = Vector.from_iterable(
                pos_rng.uniform(0.0, extent) for extent in self.size
            )
            self.spawn_plant(position, energy=pp.energy, body_radius=pp.body_radius)

    # --- the two-phase tick ---------------------------------------------------

    def tick(self) -> None:
        """Advance the world by one step: decide for all, then resolve all.

        Two phases enforce simultaneity ("brain proposes, world disposes"):

        1. **Decide (read-only).** Every living agent, in id order, perceives the
           world and returns an Action. `decide` is a pure function and mutates
           nothing, so all agents decide against the *same* un-changed world -- no
           agent gets to react to another's move within the same tick.
        2. **Resolve (write).** The world applies every collected action, then ages
           agents, charges metabolism, and removes the dead.

        Randomness is drawn from a per-tick, per-agent named sub-stream so the run
        is reproducible (iron laws 7, 8) and one agent's draws can't shift another's.
        """
        tick_rng = self._rng.spawn(f"tick/{self.tick_count}")

        # Phase 1: decide (no mutation). Build the perception grids once and share
        # them across all agents -- positions don't change during the decide phase.
        agent_grid, plant_grid = self._build_grids()
        decisions: list[tuple[int, Action]] = []
        for agent in self.agents.values():
            if not agent.alive:
                continue
            perception = self.perceive(agent, agent_grid, plant_grid)
            agent_rng = tick_rng.spawn(f"agent/{agent.id}")
            decisions.append((agent.id, agent.decision_maker.decide(perception, agent_rng)))

        # Phase 2: resolve (mutation).
        self._resolve_actions(decisions, tick_rng.spawn("resolve"))

        # Metabolism, ageing, and death -- in id order for determinism.
        for agent in self.agents.values():
            if not agent.alive:
                continue
            agent.advance_age()
            agent.spend_energy(agent.phenotype.resting_cost)
            if agent.energy <= 0.0:
                agent.mark_dead()

        # Reap the dead.
        self.agents = {aid: a for aid, a in self.agents.items() if a.alive}

        # Reproduce: survivors above their energy threshold split (after metabolism
        # and reaping, so only the living breed and newborns pay no upkeep this tick).
        self._resolve_reproduction(tick_rng.spawn("reproduce"))

        # Regrow food (fixed rate, capped) so it is reflected in this tick's snapshot.
        self._regrow_plants(tick_rng.spawn("regrow"))

        self.tick_count += 1
        self._recorder.record_tick(self.snapshot())

    def _resolve_actions(self, decisions: list[tuple[int, Action]], resolve_rng: Rng) -> None:
        """Apply all collected actions: eating first, then movement.

        **Eating resolves before movement, against tick-start positions.** A predator
        catches the prey it saw in contact at decision time; the prey cannot flee a
        bite with a move it decided in the *same* (simultaneous) tick. Agents eaten
        this tick are then skipped by the move loop. (Plant-eaters never move in the
        tick they eat -- an Action is either a MoveAction or an EatAction -- so this
        ordering leaves grazing unchanged and only matters for mobile prey.)
        """
        move_actions: list[tuple[int, MoveAction]] = []
        eat_intents: list[tuple[int, int]] = []  # (eater_id, target_id)
        for agent_id, action in decisions:
            if isinstance(action, MoveAction):
                move_actions.append((agent_id, action))
            elif isinstance(action, EatAction):
                eat_intents.append((agent_id, action.target_id))
            # Unknown action types are ignored; the brain contract is closed.

        self._resolve_eating(eat_intents, resolve_rng)

        for agent_id, action in move_actions:
            agent = self.agents.get(agent_id)
            if agent is None or not agent.alive:
                continue  # eaten this tick -> the dead don't move
            self._resolve_move(agent, action)

    def _resolve_move(self, agent: Agent, action: MoveAction) -> None:
        if action.speed_fraction <= 0.0:
            return  # resting: no displacement, no movement cost
        direction = action.direction.normalized()
        if direction.length_squared() == 0.0:
            return  # no usable direction
        speed = action.speed_fraction * agent.phenotype.max_speed
        agent.position = self.wrap(agent.position + direction * speed)
        agent.heading = direction  # face travel direction
        agent.spend_energy(agent.phenotype.move_cost(speed))

    def _in_contact(self, agent: Agent, target_position: Vector, target_radius: float) -> bool:
        """True if `agent` is touching a target: toroidal distance <= sum of radii."""
        reach = agent.phenotype.body_radius + target_radius
        return self.toroidal_delta(agent.position, target_position).length_squared() <= reach * reach

    def _resolve_eating(self, eat_intents: list[tuple[int, int]], resolve_rng: Rng) -> None:
        """Route every EatAction to its target table and resolve each.

        The brain already rolled its *willingness* to eat (B' probability) in the
        decide phase; the world is authoritative for the *physical* outcome. A target
        id resolves unambiguously (shared id space) to a plant or an agent; stale ids
        (the target died/was eaten earlier this tick) are dropped. Grazing resolves
        before predation, so a prey's final graze merely adds to the reserves its
        predator then inherits; both draw from independent named sub-streams.
        """
        plant_intents: list[tuple[int, int]] = []
        prey_intents: list[tuple[int, int]] = []
        for eater_id, target_id in eat_intents:
            if target_id in self.plants:
                plant_intents.append((eater_id, target_id))
            elif target_id in self.agents:
                prey_intents.append((eater_id, target_id))
            # else: stale / unknown target -> ignored

        self._resolve_grazing(plant_intents, resolve_rng.spawn("graze"))
        self._resolve_predation(prey_intents, resolve_rng.spawn("prey"))

    def _resolve_grazing(self, plant_intents: list[tuple[int, int]], rng: Rng) -> None:
        """Award contested plants. When several agents reach the same plant in one
        tick, a fair RNG draw picks one winner (no low-id advantage); the winner gains
        `plant_gain * plant.energy` and the plant is removed. Losers go hungry."""
        eaters_by_plant: dict[int, list[int]] = {}
        for eater_id, plant_id in plant_intents:
            eaters_by_plant.setdefault(plant_id, []).append(eater_id)

        for plant_id in sorted(eaters_by_plant):  # deterministic processing order
            plant = self.plants[plant_id]
            contenders = [
                eid for eid in eaters_by_plant[plant_id]
                if self._in_contact(self.agents[eid], plant.position, plant.body_radius)
            ]
            if not contenders:
                continue
            winner_id = contenders[0] if len(contenders) == 1 else rng.choice(contenders)
            winner = self.agents[winner_id]
            winner.add_energy(winner.phenotype.plant_gain * plant.energy)
            del self.plants[plant_id]

    def _resolve_predation(self, prey_intents: list[tuple[int, int]], rng: Rng) -> None:
        """Resolve carnivory. No-op without a predation economy (`predation_params`).

        The world re-verifies what the brain only believed: the hunter must still be
        alive, big enough (`size > size_ratio * prey.size`), and in contact (at
        tick-start positions). A prey already eaten this tick is skipped -- no double
        kill. When several qualified hunters reach one prey, a fair RNG draw picks the
        winner; it gains `prey_gain * (prey.energy + body_value_coeff * body_radius**2)`
        and the prey is marked dead (reaped at end of tick).
        """
        pp = self._predation_params
        if pp is None or not prey_intents:
            return

        hunters_by_prey: dict[int, list[int]] = {}
        for hunter_id, prey_id in prey_intents:
            hunters_by_prey.setdefault(prey_id, []).append(hunter_id)

        for prey_id in sorted(hunters_by_prey):  # deterministic processing order
            prey = self.agents.get(prey_id)
            if prey is None or not prey.alive:
                continue  # already eaten this tick -> no double kill
            prey_size = prey.genome.get("size")
            prey_radius = prey.phenotype.body_radius
            contenders = []
            for hid in hunters_by_prey[prey_id]:
                hunter = self.agents.get(hid)
                if hunter is None or not hunter.alive:
                    continue  # a hunter that was itself eaten this tick can't feed
                if hunter.genome.get("size") <= pp.size_ratio * prey_size:
                    continue  # not enough of a size advantage
                if self._in_contact(hunter, prey.position, prey_radius):
                    contenders.append(hid)
            if not contenders:
                continue
            winner_id = contenders[0] if len(contenders) == 1 else rng.choice(contenders)
            winner = self.agents[winner_id]
            meal = prey.energy + pp.body_value_coeff * prey_radius * prey_radius
            winner.add_energy(winner.phenotype.prey_gain * meal)
            prey.mark_dead()

    # --- reproduction ---------------------------------------------------------

    def _resolve_reproduction(self, rng: Rng) -> None:
        """Split every survivor whose energy reached its reproduction threshold.

        No-op without a reproduction strategy (`reproducer` is None). v1 auto-triggers
        on `energy >= repro_threshold_energy` (reproduction is not yet a brain action).
        The split is an **energy-conserving transfer**: the child gets
        `offspring_investment * parent_energy`, the parent loses exactly that -- no
        energy is created (unlike predation). High investment can empty the parent
        (sacrificial K-strategy); near-zero investment yields a non-viable child --
        both are legitimate, self-judging outcomes, not special-cased.

        The child is born near the parent (a random offset within
        `offspring_placement_factor * parent body_radius`) to create population
        viscosity (neighbours tend to be kin -- the substrate for kin selection). It
        gets a fresh random heading and `generation + 1`. Parents are snapshotted in
        id order before any birth, so newborns neither reproduce nor are iterated this
        tick (they first act next tick), keeping the pass deterministic.
        """
        if self._reproducer is None:
            return

        parents = [
            a for a in self.agents.values()
            if a.alive and a.energy >= a.phenotype.repro_threshold_energy
        ]
        for parent in parents:
            agent_rng = rng.spawn(f"agent/{parent.id}")
            child_energy = parent.energy * parent.phenotype.offspring_investment
            parent.spend_energy(child_energy)  # strict transfer (energy-conserving)

            child_genome = self._reproducer.reproduce(parent.genome, agent_rng.spawn("genome"))

            radius = self._offspring_placement_factor * parent.phenotype.body_radius
            distance = agent_rng.spawn("dist").uniform(0.0, radius)
            offset = random_unit_vector(self.size.dim, agent_rng.spawn("dir")) * distance
            child_position = self.wrap(parent.position + offset)
            heading = random_unit_vector(self.size.dim, agent_rng.spawn("heading"))

            self.spawn_agent(
                child_genome,
                child_position,
                heading=heading,
                energy=child_energy,
                generation=parent.generation + 1,
            )

    # --- inspection -----------------------------------------------------------

    def snapshot(self) -> WorldSnapshot:
        """Take an immutable, pure-data readout of the world for rendering."""
        agents = tuple(
            AgentSnapshot(
                id=a.id,
                position=a.position,
                heading=a.heading,
                body_radius=a.phenotype.body_radius,
                energy=a.energy,
                size=a.genome.get("size"),
                diet=a.genome.get("diet"),
                alive=a.alive,
            )
            for a in self.agents.values()
        )
        plants = tuple(
            PlantSnapshot(id=p.id, position=p.position, body_radius=p.body_radius)
            for p in self.plants.values()
        )
        return WorldSnapshot(
            tick=self.tick_count, size=self.size, agents=agents, plants=plants
        )

    def __repr__(self) -> str:
        return (
            f"World(tick={self.tick_count}, agents={len(self.agents)}, "
            f"size={self.size})"
        )
