"""World: the simulation container, its deterministic setup, and its snapshot.

Design decisions (see PLAN.md, Milestone 1):
- **Toroidal, agents-only (v1).** Space wraps on every axis (no walls, no edge
  effects); plants and other entities come in later milestones. The world is
  dimension-agnostic: `size` is a `Vector` of per-axis extents, so the same code
  runs a 2D plane or a 3D box.
- **Deterministic setup (iron laws 7, 8).** Everything random flows from one
  injected `Rng`. Initialization derives *named* sub-streams (`worldgen`, then
  `genome/i` / `pos/i` per agent) so the same seed reproduces the same starting
  world, and adding draws in one place can't shift another (see `rng.py`).
- **The World owns the id counter (iron law 7).** Ids are handed out by a single
  monotonic counter here, never generated by the Agent.
- **Brains stay swappable (iron law 5).** The World does NOT import a concrete
  brain. It receives a `brain_factory: (Genome) -> DecisionMaker` and calls it at
  birth, so swapping the rule-based brain for a neural net later touches only the
  factory the caller passes in -- not this module.
- **Params are injected (iron law 10).** `PhenotypeParams` and the genome schema
  come from `config` via the caller; the World hardcodes none of them.
- **Snapshots are pure data (iron laws 1, 2).** `snapshot()` returns an immutable
  `WorldSnapshot` of plain values. The rendering layer consumes only that and
  never reaches into live `Agent` objects.

This sub-step builds the container, deterministic population, and the snapshot.
The two-phase tick (decide -> resolve) and the data-recording hook land next.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from core.agent import Agent
from core.decision.base import (
    Action,
    DecisionMaker,
    EatAction,
    MoveAction,
    PerceivedAgent,
    PerceivedPlant,
    Perception,
)
from core.genome import ChromosomeSpec, Genome
from core.phenotype import PhenotypeParams, express
from core.plant import Plant, PlantParams
from core.recording import NullRecorder, Recorder
from core.rng import Rng
from core.vector import Vector

BrainFactory = Callable[[Genome], DecisionMaker]


def _random_unit_vector(dim: int, rng: Rng) -> Vector:
    """An isotropic random unit vector (Gaussian per component, then normalize).

    Dimension-agnostic. (Mirrors the helper in `decision.rule_based`; kept local to
    avoid the World depending on a concrete brain module.)
    """
    v = Vector(*(rng.gauss(0.0, 1.0) for _ in range(dim)))
    if v.length_squared() == 0.0:
        return Vector(*([1.0] + [0.0] * (dim - 1)))  # astronomically unlikely
    return v.normalized()


# --- pure-data snapshots (rendering layer consumes only these) ----------------

@dataclass(frozen=True, slots=True)
class AgentSnapshot:
    """An immutable readout of one agent at a moment in time.

    Carries what a renderer or recorder needs without exposing the live Agent:
    pose (`position`, `heading`, `body_radius`) for drawing, `size`/`diet` for
    colour, `energy` for debug overlays, `alive` for filtering.
    """

    id: int
    position: Vector
    heading: Vector
    body_radius: float
    energy: float
    size: float
    diet: float
    alive: bool


@dataclass(frozen=True, slots=True)
class PlantSnapshot:
    """An immutable readout of one plant for rendering."""

    id: int
    position: Vector
    body_radius: float


@dataclass(frozen=True, slots=True)
class WorldSnapshot:
    """An immutable readout of the whole world at one tick."""

    tick: int
    size: Vector
    agents: tuple[AgentSnapshot, ...]
    plants: tuple[PlantSnapshot, ...]


# --- the world ----------------------------------------------------------------

class World:
    """Container for the live simulation state plus deterministic setup."""

    __slots__ = (
        "size",
        "agents",
        "plants",
        "tick_count",
        "_rng",
        "_schema",
        "_phenotype_params",
        "_brain_factory",
        "_next_id",
        "_recorder",
        "_plant_params",
    )

    def __init__(
        self,
        size: Vector,
        rng: Rng,
        *,
        schema: tuple[ChromosomeSpec, ...],
        phenotype_params: PhenotypeParams,
        brain_factory: BrainFactory,
        recorder: Recorder | None = None,
        plant_params: PlantParams | None = None,
    ) -> None:
        if any(extent <= 0 for extent in size):
            raise ValueError("every world extent must be positive")
        self.size = size
        # Keyed by id: O(1) target lookup for EatAction in the resolve phase, and
        # dict preserves insertion (== id) order, keeping iteration deterministic.
        # Agents and plants share one id space (the same counter) so an
        # EatAction(target_id) resolves unambiguously to one table or the other.
        self.agents: dict[int, Agent] = {}
        self.plants: dict[int, Plant] = {}
        self.tick_count = 0
        self._rng = rng
        self._schema = schema
        self._phenotype_params = phenotype_params
        self._brain_factory = brain_factory
        self._next_id = 0
        # Data-recording seam (iron law 6): default is a no-op sink.
        self._recorder = recorder if recorder is not None else NullRecorder()
        # Plant economy (optional): when set, tick() regrows plants each step.
        self._plant_params = plant_params

    # --- id allocation (World owns the counter, iron law 7) -------------------

    def _allocate_id(self) -> int:
        new_id = self._next_id
        self._next_id += 1
        return new_id

    # --- geometry -------------------------------------------------------------

    def wrap(self, position: Vector) -> Vector:
        """Wrap a position into the toroidal world (modulo each axis extent)."""
        if position.dim != self.size.dim:
            raise ValueError("position dimension does not match world dimension")
        return Vector.from_iterable(
            comp % extent for comp, extent in zip(position, self.size)
        )

    def toroidal_delta(self, source: Vector, target: Vector) -> Vector:
        """Shortest displacement from `source` to `target` on the torus.

        Minimum-image convention: on each axis, take whichever of "go forward" or
        "wrap around the back" is shorter. This is what makes neighbours on the
        opposite edge count as close.
        """
        if source.dim != self.size.dim or target.dim != self.size.dim:
            raise ValueError("vector dimension does not match world dimension")
        comps = []
        for s, t, extent in zip(source, target, self.size):
            d = (t - s) % extent          # in [0, extent)
            if d > extent / 2.0:
                d -= extent               # wrapping backwards is shorter
            comps.append(d)
        return Vector.from_iterable(comps)

    # --- perception (sector / cone vision) ------------------------------------

    def _visible_delta(
        self,
        observer: Vector,
        target: Vector,
        heading_unit: Vector,
        range_sq: float,
        cos_half: float,
    ) -> Vector | None:
        """Return the relative position of `target` if the observer can see it, else
        None. Visible = within range AND inside the forward cone.

        The field-of-view test is a dot product between the observer's unit heading
        and the unit direction to the target, so it is dimension-agnostic (a 2D
        sector now, a 3D cone later). An entity in contact (same spot) is always
        visible.
        """
        rel = self.toroidal_delta(observer, target)
        dist_sq = rel.length_squared()
        if dist_sq > range_sq:
            return None
        if dist_sq > 0.0 and heading_unit.dot(rel.normalized()) < cos_half:
            return None
        return rel

    def perceive(self, agent: Agent) -> Perception:
        """Gather what `agent` can see this tick into a Perception value object.

        An entity is perceived when it is within `perception_range` by toroidal
        distance and inside the field of view (see `_visible_delta`). Plants and
        agents are filtered by the same vision; a plant behind the agent is unseen.
        """
        pheno = agent.phenotype
        range_sq = pheno.perception_range * pheno.perception_range
        cos_half = pheno.perception_cos_half_angle
        heading_unit = agent.heading.normalized()

        seen_agents: list[PerceivedAgent] = []
        for other in self.agents.values():
            if other.id == agent.id or not other.alive:
                continue
            rel = self._visible_delta(
                agent.position, other.position, heading_unit, range_sq, cos_half
            )
            if rel is None:
                continue
            seen_agents.append(
                PerceivedAgent(
                    id=other.id,
                    relative_position=rel,
                    size=other.genome.get("size"),
                    diet=other.genome.get("diet"),
                    body_radius=other.phenotype.body_radius,
                )
            )

        seen_plants: list[PerceivedPlant] = []
        for plant in self.plants.values():
            rel = self._visible_delta(
                agent.position, plant.position, heading_unit, range_sq, cos_half
            )
            if rel is None:
                continue
            seen_plants.append(
                PerceivedPlant(
                    id=plant.id,
                    relative_position=rel,
                    body_radius=plant.body_radius,
                )
            )

        return Perception(
            nearby_agents=tuple(seen_agents),
            nearby_plants=tuple(seen_plants),
            own_energy=agent.energy,
            own_phenotype=pheno,
            own_heading=agent.heading,
        )

    # --- birth ----------------------------------------------------------------

    def spawn_agent(
        self,
        genome: Genome,
        position: Vector,
        *,
        heading: Vector | None = None,
        energy: float = 0.0,
        generation: int = 0,
    ) -> Agent:
        """Create an agent from a genome: express its phenotype + brain, assign an
        id, wrap it into the torus, and register it. Returns the new Agent."""
        phenotype = express(genome, self._phenotype_params)
        brain = self._brain_factory(genome)
        agent = Agent(
            self._allocate_id(),
            genome,
            phenotype,
            self.wrap(position),
            heading=heading,
            energy=energy,
            generation=generation,
            decision_maker=brain,
        )
        self.agents[agent.id] = agent
        return agent

    def populate(self, count: int, *, initial_energy: float) -> None:
        """Deterministically fill the world with `count` random agents.

        Same (world seed, count) -> identical starting population. Each agent's
        genome and position draw from their own named sub-streams so the layout is
        stable even if draw counts change elsewhere.
        """
        if count < 0:
            raise ValueError("count cannot be negative")
        gen_rng = self._rng.spawn("worldgen")
        for i in range(count):
            genome = Genome.random(self._schema, gen_rng.spawn(f"genome/{i}"))
            pos_rng = gen_rng.spawn(f"pos/{i}")
            position = Vector.from_iterable(
                pos_rng.uniform(0.0, extent) for extent in self.size
            )
            # A random unit facing so directional vision works from birth; its own
            # named sub-stream keeps positions stable regardless of this draw.
            heading = _random_unit_vector(self.size.dim, gen_rng.spawn(f"heading/{i}"))
            self.spawn_agent(
                genome, position, heading=heading,
                energy=initial_energy, generation=0,
            )

    # --- plants ---------------------------------------------------------------

    def spawn_plant(self, position: Vector, *, energy: float, body_radius: float) -> Plant:
        """Create a plant at `position` (wrapped into the torus) and register it.
        Shares the agent id counter so EatAction targets stay unambiguous."""
        plant = Plant(self._allocate_id(), self.wrap(position), body_radius, energy)
        self.plants[plant.id] = plant
        return plant

    def scatter_plants(self, count: int, *, energy: float, body_radius: float) -> None:
        """Deterministically scatter `count` plants uniformly at random.

        Uses its own named sub-stream so plant placement is reproducible and
        independent of how many draws the agent population consumed.
        """
        if count < 0:
            raise ValueError("count cannot be negative")
        plant_rng = self._rng.spawn("plantgen")
        for i in range(count):
            pos_rng = plant_rng.spawn(f"pos/{i}")
            position = Vector.from_iterable(
                pos_rng.uniform(0.0, extent) for extent in self.size
            )
            self.spawn_plant(position, energy=energy, body_radius=body_radius)

    def _regrow_plants(self, rng: Rng) -> None:
        """Scatter up to `regen_per_tick` new plants, capped at `max_count`.

        No-op when the world has no plant economy (`plant_params` is None). Because
        this runs every tick, the food supply recovers even after being grazed flat
        -- it can never be permanently eaten to zero.
        """
        pp = self._plant_params
        if pp is None:
            return
        room = pp.max_count - len(self.plants)
        to_add = min(pp.regen_per_tick, room)
        for i in range(to_add):  # to_add <= 0 -> no iterations
            pos_rng = rng.spawn(f"pos/{i}")
            position = Vector.from_iterable(
                pos_rng.uniform(0.0, extent) for extent in self.size
            )
            self.spawn_plant(position, energy=pp.energy, body_radius=pp.body_radius)

    # --- the two-phase tick ---------------------------------------------------

    def tick(self) -> None:
        """Advance the world by one step: decide for all, then resolve all.

        Two phases enforce simultaneity ("brain proposes, world disposes"):

        1. **Decide (read-only).** Every living agent, in id order, perceives the
           world and returns an Action. `decide` is a pure function and mutates
           nothing, so all agents decide against the *same* un-changed world -- no
           agent gets to react to another's move within the same tick.
        2. **Resolve (write).** The world applies every collected action, then ages
           agents, charges metabolism, and removes the dead.

        Randomness is drawn from a per-tick, per-agent named sub-stream so the run
        is reproducible (iron laws 7, 8) and one agent's draws can't shift another's.
        """
        tick_rng = self._rng.spawn(f"tick/{self.tick_count}")

        # Phase 1: decide (no mutation).
        decisions: list[tuple[int, Action]] = []
        for agent in self.agents.values():
            if not agent.alive:
                continue
            perception = self.perceive(agent)
            agent_rng = tick_rng.spawn(f"agent/{agent.id}")
            decisions.append((agent.id, agent.decision_maker.decide(perception, agent_rng)))

        # Phase 2: resolve (mutation).
        self._resolve_actions(decisions, tick_rng.spawn("resolve"))

        # Metabolism, ageing, and death -- in id order for determinism.
        for agent in self.agents.values():
            if not agent.alive:
                continue
            agent.advance_age()
            agent.spend_energy(agent.phenotype.resting_cost)
            if agent.energy <= 0.0:
                agent.mark_dead()

        # Reap the dead.
        self.agents = {aid: a for aid, a in self.agents.items() if a.alive}

        # Regrow food (fixed rate, capped) so it is reflected in this tick's snapshot.
        self._regrow_plants(tick_rng.spawn("regrow"))

        self.tick_count += 1
        self._recorder.record_tick(self.snapshot())

    def _resolve_actions(self, decisions: list[tuple[int, Action]], resolve_rng: Rng) -> None:
        """Apply all collected actions: movement is independent per agent; eating is
        resolved as a group because several agents may target the same food.

        Order is immaterial in v1: an eater does not move and plants are stationary,
        so contact is unaffected by other agents' moves. (Moving prey arrives with
        the predation sub-step, which will revisit this.)
        """
        eat_intents: list[tuple[int, int]] = []  # (eater_id, target_id)
        for agent_id, action in decisions:
            agent = self.agents[agent_id]
            if isinstance(action, MoveAction):
                self._resolve_move(agent, action)
            elif isinstance(action, EatAction):
                eat_intents.append((agent_id, action.target_id))
            # Unknown action types are ignored; the brain contract is closed.
        self._resolve_eating(eat_intents, resolve_rng)

    def _resolve_move(self, agent: Agent, action: MoveAction) -> None:
        if action.speed_fraction <= 0.0:
            return  # resting: no displacement, no movement cost
        direction = action.direction.normalized()
        if direction.length_squared() == 0.0:
            return  # no usable direction
        speed = action.speed_fraction * agent.phenotype.max_speed
        agent.position = self.wrap(agent.position + direction * speed)
        agent.heading = direction  # face travel direction
        agent.spend_energy(agent.phenotype.move_cost(speed))

    def _in_contact(self, agent: Agent, target_position: Vector, target_radius: float) -> bool:
        """True if `agent` is touching a target: toroidal distance <= sum of radii."""
        reach = agent.phenotype.body_radius + target_radius
        return self.toroidal_delta(agent.position, target_position).length_squared() <= reach * reach

    def _resolve_eating(self, eat_intents: list[tuple[int, int]], resolve_rng: Rng) -> None:
        """Resolve plant grazing. (Prey targets are deferred to the predation sub-step.)

        The brain already rolled its *willingness* to eat (B' probability) in the
        decide phase; the world is authoritative for the *physical* outcome: it
        re-checks contact and arbitrates conflicts. When several agents reach the
        same plant in one tick, a fair RNG draw picks one winner (no low-id
        advantage); the winner gains `plant_gain * plant.energy` and the plant is
        removed. Losers go hungry this tick.
        """
        eaters_by_plant: dict[int, list[int]] = {}
        for eater_id, target_id in eat_intents:
            if target_id in self.plants:  # ignore prey / stale targets in v1
                eaters_by_plant.setdefault(target_id, []).append(eater_id)

        for plant_id in sorted(eaters_by_plant):  # deterministic processing order
            plant = self.plants[plant_id]
            contenders = [
                eid for eid in eaters_by_plant[plant_id]
                if self._in_contact(self.agents[eid], plant.position, plant.body_radius)
            ]
            if not contenders:
                continue
            winner_id = contenders[0] if len(contenders) == 1 else resolve_rng.choice(contenders)
            winner = self.agents[winner_id]
            winner.add_energy(winner.phenotype.plant_gain * plant.energy)
            del self.plants[plant_id]

    # --- inspection -----------------------------------------------------------

    def snapshot(self) -> WorldSnapshot:
        """Take an immutable, pure-data readout of the world for rendering."""
        agents = tuple(
            AgentSnapshot(
                id=a.id,
                position=a.position,
                heading=a.heading,
                body_radius=a.phenotype.body_radius,
                energy=a.energy,
                size=a.genome.get("size"),
                diet=a.genome.get("diet"),
                alive=a.alive,
            )
            for a in self.agents.values()
        )
        plants = tuple(
            PlantSnapshot(id=p.id, position=p.position, body_radius=p.body_radius)
            for p in self.plants.values()
        )
        return WorldSnapshot(
            tick=self.tick_count, size=self.size, agents=agents, plants=plants
        )

    def __repr__(self) -> str:
        return (
            f"World(tick={self.tick_count}, agents={len(self.agents)}, "
            f"size={self.size})"
        )
